name: Fetch Installation Paths

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6 AM UTC
  workflow_dispatch:     # Allow manual runs

jobs:
  run-pytoon-script:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code 
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: |
          python -m pip install requests
          python fetch_rmm_tool.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add installation_paths.txt
          git commit -m "Update installation_paths.txt"
          git push
